FROM thecodingmachine/workadventure-play:latest

# Si ton Dockerfile est dans play/, remonte pour copier depuis play/
COPY ./src/front/components/images /usr/src/app/src/front/components/images
COPY ./public/static /usr/src/app/public/static